apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roboshop-ebs-claim-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop-ebs-sc
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-ebs-pod
  labels:
    purpose: ebs-dynamic-demo
    project: roboshop
spec:
  containers:
  - name: roboshop-ebs-pod
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: roboshop-ebs-claim-dynamic