apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05916debc5660a783

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roboshop-efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-static-efs
  labels:
    purpose: efs-static-demo
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: roboshop-efs-claim

---
apiVersion: v1
kind: Service
metadata:
  name: efs-static
  labels:
    purpose: efs-static-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port