apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-roboshop-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-roboshop-pod
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-dynamic-claim

---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic-service
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port